#!/bin/bash

SONG=$(mpc current)
STATUS=$(mpc status | tail -2 | head -1 | cut -d' ' -f1 | tr -d '[]')

case "${STATUS}" in
  "playing" )
    echo "${SONG}" # full_text
    echo "" # short_text
    ;;

  "paused" )
    echo "[paused] ${SONG}" # full_text
    echo "" # short_text
    ;;

  * )
    ;; # nop
esac
