#!/bin/bash

VOL=$(pamixer --get-volume)
MUTE=$(pamixer --get-mute)

if [[ "${MUTE}" = true ]] ; then
  echo "mute"    # full_text
  echo "mute"    # short_text
  echo "#ffff00" # color
elif [[ "${VOL}" != "" ]] ; then
  echo "vol $VOL%" # full_text
  echo "vol $VOL%" # short_text
fi
