#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then xrdb -merge $sysresources ; fi
if [ -f $sysmodmap ]; then xmodmap $sysmodmap ; fi
if [ -f "$userresources" ]; then xrdb -merge "$userresources" ; fi
if [ -f "$usermodmap" ]; then xmodmap "$usermodmap" ; fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# update touchpad driver properties
xinput set-prop "DELL0741:00 06CB:7E7E Touchpad" 304 1
xinput set-prop "DELL0741:00 06CB:7E7E Touchpad" 314 0

export WINEARCH=win64

# start i3
exec i3
