#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then xrdb -merge $sysresources ; fi
if [ -f $sysmodmap ]; then xmodmap $sysmodmap ; fi
if [ -f "$userresources" ]; then xrdb -merge "$userresources" ; fi
if [ -f "$usermodmap" ]; then xmodmap "$usermodmap" ; fi

# start systemwide defaults.
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# set cursor repeat rate
xset r rate 200 30

# set wine system architecture
export WINEARCH=win64

# Host-specific extensions/overrides.
if [[ -f .xinitrc.host ]] ; then . .xinitrc.host ; fi

# start i3
exec i3
