#!/bin/bash

CPUS=12
CRITICAL=1200
WARN=600

LOAD=$(cat /proc/loadavg | awk -F ' ' '{print $1}')

if [[ "${LOAD}" != "" ]] ; then
  # Scale load by the number of CPUs
  SCALED_LOAD=$(echo "scale=4; ${LOAD} / ${CPUS}" | bc -l)
  LOAD_PERC=$(echo "scale=0; ${SCALED_LOAD} * 100" | bc -l)
  LOAD_PERC=${LOAD_PERC%.*}

  echo "cpu ${LOAD_PERC}%" # full_text
  echo "${LOAD_PERC}%" # short_text

  # Set critical/warn flags.
  [[ ${LOAD_PERC} -ge "${CRITICAL}" ]] && exit 33
  [[ ${LOAD_PERC} -ge "${WARN}" ]] && echo "#FF8000"
fi
